#+TITLE: Optimal portfolio selection and the problem of estimating return moments
#+AUTHOR: Christian Groll
#+DATE: 1. July 2014

#+CATEGORY: financial_econometrics
#+TAGS: asset_mgmt, Markowitz, presentation
#+DESCRIPTION: analyse performance of Markowitz portfolios 

#+LaTeX_CLASS: beamer
#+BEAMER_THEME: Frankfurt

#+LATEX_HEADER: \usepackage{amsmath}
#+LaTeX_HEADER: \usepackage{geometry}
#+LaTeX_HEADER: \usepackage{subfigure}
#+LaTeX_HEADER: \usepackage{graphicx}
#+LaTeX_HEADER: \usepackage{caption}

#+OPTIONS: d:nil
#+OPTIONS: H:2
#+OPTIONS: toc:nil
#+OPTIONS: todo:t
#+OPTIONS: tags:nil
#+OPTIONS: skip:on
#+OPTIONS: ^:nil
#+OPTIONS: eval:never-export
#+EXCLUDE_TAGS: notes

#+PROPERTY: exports both
#+PROPERTY: results output
#+PROPERTY: tangle yes
#+PROPERTY: dir ./src_results/

#+LATEX_HEADER: \setbeamertemplate{footline}[page number] 
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

#+BEGIN_SRC comment :eval never :exports none
the following line does include toc after each section!
however, preview-latex does not work with it!
#+startup: beamer

#+LATEX_HEADER: \subtitle{{\color{red} work in progress}}
#+END_SRC

#+BEGIN_SRC comment :eval never :exports none
Note: 
- final slides can be found under
  ~/work/presentations/slides_ss14_optimal_portfolio_selection_asset_pricing_julia.pdf
- new export would require references.bib file, but link was broken
#+END_SRC


** Motivation
*** traditional notion of risk management
estimation of risk for *given* and *immutable* portfolio composition 

*** proceed with list without box                           :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- unrealistic (especially for longer horizons):
  - portfolio managers most likely adapt if some asset's risk
    increases relative to others 
  - some investment strategies are explicitly build on portfolio
    re-balancing (duration-based hedging strategies) 

- no guideline on portfolio selection itself: what is optimal
  investment strategy if risk is taken into account 

$\Rightarrow$ asset management as a natural extension to risk
management (Solvency II)


** Motivation
Original intention:
- Markowitz
- factor models
  - reduce dimensions
  - robust estimation of covariance matrix
  - interpretable structure $\Rightarrow$ false sense of control
    through linear sensitivities

Crucial part of Markowitz: expected returns 
*** Asset pricing theory
- better estimation
- reveal time-variation
$\Rightarrow$ predictability?


** Motivation                                                         :notes:
Hence, I did set up to get acquainted with asset management
- Markowitz: Jasic did wake my interest
- factor models:
  - dimension reduction: market-wide driving factors
  - interpretable structure required for actively intervening and
    selecting assets
  - industry standard

First moments: I didn't really spent a lot of attention on them

How much information is in conditional expectations? Does it allow
predictability? 
- asset pricing / return predictability usually only slightly referred
  to 
- link to Benjamin's talk 
  - compared to his results, my talk will be quite unimpressive
  - think about basics: what patterns exist in first moments of assets 


** Outline
#+LaTeX: \tableofcontents

* Asset pricing


** Basic assumption 

Following \cite{rv_coch_2009_asset_pricing}: consumption based model

- people are *expected utility maximizers*: with future wealth $X$ and
  utility function $U$, the optimization problem is

$$\underset{\xi}{\max}\ \mathbb{E}[U(X(\xi))]$$


- people are *risk-averse*: utility $U$ increases with money ($U'>0$),
  but marginal utility of money decreases ($U''<0$)

** Risk-aversion                                                      :notes:
"We dislike vast uncertainty in lifetime wealth because a dollar that
helps us avoid poverty is more valuable than a dollar that helps us
become very rich." \cite{rv_rabin_2000_risk_aversion_expected_theory} 

** Concave utility
- due to concavity, uncertainty inherent to future wealth negatively
  affects expected utility

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/concave_utility.jpg}
#+LATEX: \end{figure}

#+BEGIN_LaTeX
   \begin{itemize}
   \item[$\Rightarrow$] for given expectation, cash flow distributions with 
     lower volatility are preferred 
   \end{itemize}
#+END_LaTeX


** Basic assumption notes                                             :notes:

- builds on Cochrane's consumption based model

- any additional euro to profits is worth less utility than any
  additional lost euro -> better formulation

** Consequences for wealth components

#+BEGIN_LaTeX
   \action<+->{Components of future wealth:}
   \begin{itemize}
   \item<+-> assets: prices, dividends
     \begin{itemize}
     \item[$\Rightarrow$]<+-> if assets are unique component: higher asset
       volatility needs to be compensated through higher expected returns
     \end{itemize}
   \end{itemize}
#+END_LaTeX

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02.jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(1).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(2).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(3).jpg}
#+LATEX: \end{figure}


** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(4).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If all market participants derive the same utility:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(5).jpg}
#+LATEX: \end{figure}

$\Rightarrow$ assets have *different expected returns*, but *equal
expected utility* 

** Notes                                                              :notes:
Picture only shows what future wealth is worth to me. Prices would be
determined through supply and demand at the market. 

If prices coincide with my own appreciation, both assets have
different expected returns, but equal expected utility.

Also: what happens, if volatility changes, while I already have the
asset? 
- price decreases
- given new price level, expected return increases
- given old price level, expected return stays the same, but
  volatility has increased

** Wealth components

#+BEGIN_LaTeX
   Components of future wealth:
   \begin{itemize}
   \item<+-> assets: prices, dividends
     \begin{itemize}
     \item[$\Rightarrow$] if assets are unique component: higher portfolio
       volatility needs to be compensated through higher expected returns
       (\alert{Markowitz})
     \item[$\Rightarrow$]<+-> if all market participants hold all assets:
       \begin{itemize}
       \item portfolio volatility directly depends on asset correlations
       \item compensation for systemic risk only (\alert{CAPM})
       \end{itemize}
     \item[$\Rightarrow$]<+-> \alert{too simplistic}: asset cash flows
       are not the only determinant of your future wealth
     \end{itemize}
   \item<+-> job income 
   \item<+-> losses due to catastrophic events
   \item[$\Rightarrow$]<+-> utility is derived from \alert{overall} cash
     flow distribution: hedge individual components to diminish overall
     volatility 
   \end{itemize}
#+END_LaTeX


** Examples: choose your preferred asset
Given two assets *A* and *B* with *identical* return distributions
($F_{A}\sim F_{B}$), which one would you prefer?

#+BEGIN_LaTeX
   \begin{itemize}
   \item<+-> You are working for Microsoft. Stock A is of Microsoft, while
     stock B is of Walmart.
   \item<+-> You have property within an earthquake zone. Stock A is of
     Walmart, stock B is of a large reinsurance company.
   \end{itemize}
   
   \begin{block}{Investment rule}<+->
     All other things equal, you prefer assets that are valuable when you
     need them.
   \end{block}
#+END_LaTeX

** Further explanation of "when"                                      :notes:
In other words: if an asset tends to have its low price events exactly
when you would need it, then you would require compensation for this
fact. 

"When" could mean:
- a given point in time -> evolution up to this event does not matter
  (10 year bond)
- a given state of nature -> need to sell asset only when I lose job 

** Price effect
market participants require *compensation* for an asset's correlation
to personal risks:
#+BEGIN_LaTeX
   \begin{itemize}
   \item[$\Rightarrow$] future cash flow less worthwhile
   \item[$\Rightarrow$] lower price
   \item[$\Rightarrow$] higher expected return
   \end{itemize}
#+END_LaTeX

*** Improved estimation
knowledge of the correlation between an asset and the personal risks
of market participants should allow better estimation of expected
returns (benefits for Markowitz)

** Three types of risk
Risks, that
- *only you have*, but nobody else: assets correlated with your risk
  generate lower expected utility
- *you and everybody else has*: assets correlated with these risks
  exhibit higher expected returns to cause same level of utility
- *everybody else has, but you don't*: assets correlated with these
  risks exhibit higher expected returns, and also generate higher
  levels of utility $\Rightarrow$ *investment opportunity*

*** 
How should this be taken into account in portfolio selection? 

How is this reflected in Markowitz portfolio optimization?

** Possible approaches
In order to find the *overall utility* maximizing portfolio, we could:
- *model overall distribution* including all wealth components (too
  ambitious)
- perfectly *hedge personal risks* through insurance: optimizing
  portfolio without taking into account personal risks should be good
  approximation 

But: what happens without perfectly hedged personal risks, if we still
optimize with respect to assets only?

** Reality check
#+BEGIN_LaTeX
   \begin{block}{Personal check}<+->
     \begin{itemize}
     \item are all your personal risks hedged through insurance?
     \item if not: which of the remaining risks could be hedged through stocks?
       (if shared by other market participants: leading to lower expected
       returns for some assets) 
     \end{itemize}
   \end{block}

#+END_LaTeX


#+BEGIN_LaTeX
   \begin{block}{Market check}<+->
     Some stocks \alert{persistently exhibit higher expected returns} than others.
     \begin{itemize}
     \item compensation for personal risks? 
       \begin{itemize}
       \item consumption based model
       \item should you require same compensation?
       \end{itemize}
     \item market inefficiency?
     \end{itemize}
   \end{block}

#+END_LaTeX





** Markowitz

For any given expected portfolio return $\mu^{*}$, minimize portfolio variance:
*** 
\begin{align*}
\underset{\xi}{\min}\, \xi'\Sigma\xi & \\
\text{ subject to } \xi'\mu &=\mu^{*},\\
\xi'\bf{1} &=1
\end{align*}

*** proceed with list without box                           :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
\Rightarrow assets with *low volatility* and *low correlations* to other assets
are preferred 

\Rightarrow correlation to personal risks is unconsidered

** Markowitz deficiency
If *personal risks really exist* that require additional compensation,
Markowitz will fail:

- risks that only you have:
  - Markowitz fails to require compensation for correlation to
    personal risks

- risks that you and everybody else have: 
  - compensation in form of higher expected returns is mis-interpreted
    with higher utility, and one will falsely concentrate on these
    assets

** Consequences of higher expected return patterns

Inefficient market: 
#+BEGIN_LaTeX
   \begin{itemize}
   \item patterns of higher expected returns are \alert{irrational}
   \item you do not require compensation for these risks
   \item[$\Rightarrow$] aggressively exploit higher expected returns
   \end{itemize}
\vspace{5 mm}
#+END_LaTeX

Efficient market:
- there are risks that all market participants want to be compensated
  for
- should you require the same compensation?

As long as you are not affected by the risks that all other market
participants seem to bother about, Markowitz works
#+BEGIN_LaTeX
   \begin{itemize}
   \item[$\Rightarrow$] investment opportunities 
   \end{itemize}
#+END_LaTeX


** Adaptions of Markowitz 

Given some personal risks exist, how could Markowitz be adapted?
- return characteristics of assets should be adapted to take
  compensation into account
  - risk neutral probabilities
  - artificially scale down $\mu$ of risk factors
  - penalize correlation to some given risk factors
\Rightarrow based on which data?

** My approach


#+BEGIN_LaTeX
   \begin{itemize}
   \item no personal risks identified
   \item[$\Rightarrow$] no compensation required
   \item[$\Rightarrow$] Markowitz works out of the box 
   \item estimating moments based on observable patterns of expected returns
   \end{itemize}
#+END_LaTeX

If risk factors are not taken into account during portfolio selection,
at least they should be looked at during risk management:
- knowing sensitivities to risk factors (under which circumstances do
  we exceed VaR)
- risk management: taking re-financing costs into account
  (asset-liability management)

** Doubts                                                             :notes:
Or: should we probably incorporate risk factors anyways? Maybe they do
not matter to us at all, but still will require higher refinancing
costs in certain states of nature!

** Consequences for Markowitz                                         :notes:
some general form of job risk / market risk should already be included
- market risk -> penalized through correlation
- idiosyncratic risk -> penalized through high volatility, in the
  limit vanishing, as one would expect

** CAPM remarks                                                       :notes:

Risks that only you have: idiosyncratic risk
- not compensated
- assume you are holding single asset
  - single asset with $\beta=0$ 
  - asset volatility largely drives overall volatility of utility
  - you would want compensation on this risk!

CAPM holds, if all wealth arises from assets only, and all investors
invest in all assets. If we switch to a world with multiple wealth
components, should we still expect risk premiums on $\beta$ values?
- assets still could make up a large fraction of overall wealth
- and: high $\beta$ values also correlate with other important
  components: job!

Risks that everybody has: intuitive $\beta$ explanation
- recession increases likelihood of job losses
- in case of job loss, fall back on assets
- recession also decreases asset prices
- hence: assets are comparatively worthless when they are needed most 
- extra compensation


* Teaser

** Fama-French

From
\cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies}:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=\linewidth]{unreplicatable_pics/fama_french_size_hml.png}
#+LATEX: \end{figure}

** Momentum
From \cite{rv_asnes_fraz_2014_fact_fiction_momentum_investing}:
#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=\linewidth]{unreplicatable_pics/momentum.png}
#+LATEX: \end{figure}

** Dividend yields
From \cite{rv_coch_2009_asset_pricing}:
#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.8\linewidth]{unreplicatable_pics/cochrane_dividend_yield.png}
#+LATEX: \end{figure}

** References
#+LATEX: \bibliographystyle{apalike}
#+LATEX: \bibliography{references.bib}


* Further problems                                                    :notes:
** General Markowitz problems
Problems related to asset pricing theory: 
- estimation problems for \mu
- sole $\mu$-$\Sigma$ optimization is not enough
- multi-period extension
- estimation risk (overconfidence / bootstrap)
- mean-variance efficiency does not equal utility maximization 


** Pitfalls of utility theory
- in our models risk aversion usually is captured through concave
  utility function over wealth
- problem: \cite{rv_rabin_2000_risk_aversion_expected_theory}
  - turning down a modest-stakes gamble means that the marginal
    utility of money must diminish very quickly for small changes in
    wealth
  - anything but virtual risk neutrality over modest stakes implies
    manifestly unrealistic risk aversion over large stakes 

$\Rightarrow$ utility theory unable to replicate human behavior over
large range of wealth levels?

** paper name                                                         :notes:
Risk aversion and expected-utility theory: A calibration theorem.

** Decay of marginal utility of money
*** Question 
How much is the 100th dollar worth compared to the 1000th?

$$ U(\$(100)) \cdot c = U(\$(1000)) $$

*** proceed with list without box                           :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
You have 100\$. Let's assume that you would turn down the following
game:
- heads: you *lose* 10\$
- tails: you *win* 11\$
What can be inferred about the decay of marginal utility of money? 

** Decay of marginal utility of money

what does refraining from participation $\Leftrightarrow$ 
$$0.5\sum_{i=91}^{100} U(\$(i)) >0.5\sum_{i=101}^{111} U(\$(i))$$

tell us about $$U(\$(91))\cdot c = U(\$(111))?$$

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.7\linewidth]{unreplicatable_pics/pitfalls_utility_theory_04.jpg}
#+LATEX: \end{figure}

** Decay of marginal utility of money

Due to
\begin{align*}
10\cdot U(\$(91)) &>\sum_{i=91}^{100} U(\$(i)) \\
&>\sum_{i=101}^{111} U(\$(i)) \\
&> 11\cdot U(\$(111))
\end{align*}

we get 
$$U\left(\$(91)\right) \frac{10}{11}> U\left(\$(111)\right)$$

And, still rejecting the game with initial wealth 121\$:
$$U(\$(91)) \left( \frac{10}{11} \right)^{2}> U(\$(131))$$

** Decay of marginal utility of money
#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=\linewidth]{unreplicatable_pics/rabin_table.png}
#+LATEX: \end{figure}




* Return predictability                                               :notes:
** More realistic factors: Fama / French
But: some risks (less interpretable) are not hedged and hence show
higher returns 


- what would be real risk factors that one would tried to hedge /
  avoid with assets?
- real world factors do not provide such an easy interpretation: Fama
  / French 

** Pricing anomalies
Fama French model
\cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 

- average returns are said to be related to firm characteristics:
  - size
  - earnings / price
  - cash flow / price
  - book-to-market equity
  - past sales growth
  - long-term and short-term past return
- explanation: 
  - CAPM fails (anomalies)
  - consumption based model?

** Fama French three factor model

Time series regression: index t?!
$$R_{i}-R_{f}=\alpha_{i}+b_{i}(R_{M}-R_{f}) + s_{i}SMB + h_{i}HML + \epsilon_{i}$$

$$\mathbb{E}[R_{i}]- R_{f}=b_{i}  \left( \mathbb{E}[R_{M}-R_{f}] \right) +
s_{i}\mathbb{E}[SMB] + h_{i}\mathbb{E}[HML]$$

HML: proxy for relative stress: 
- weak firms with persistently low earnings tend to have high BE/ME
  (comparatively low prices) and positive slopes on HML 


** Momentum
- firms with low long-term returns tend to have higher future returns
  \cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 
- short-term returns tend to continue \cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 

through FF3: stocks with low long-term past returns (losers) tend to
have positive SMB and HML slopes (they are smaller and relatively
distressed) 
- continuation of short-term returns not explained by FF3

SMB and HML mimic combinations of two underlying risk factors or state
variables of special hedging concern to investors.




** Fama French
- allegedly, some common risk factors could be identified: Fama /
  French 
- no volatility compensation: if everybody else has a large and
  diversified portfolio, they do not bother about idiosyncratic risks 
- factor models (industry standard)

- forecasting returns:
  - allegedly, according to Cochrane, future annual returns could be
    forecast through dividend price ratios
  - consequences for higher frequency returns?
    - simple shift of means is not sufficient!

** incorporating low frequency information into high frequency data 

* Julia

** Benefits
- speed
- free and open source (MIT license)
- expressive language
- IJulia IDE
  - combining code, text, graphics, LaTeX, multimedia
  - exportation to pdf, html or html slides
- transparency
  - github
  - testing: automatic build test / code coverage

** Speed benchmarks
#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=\linewidth]{unreplicatable_pics/julia_benchmarks.png}
#+LATEX: \end{figure}

** IJulia: story telling with data                                    :notes:

Export:
- pdf (using LaTeX)
- [[http://nbviewer.ipython.org/gist/cgroll/bcc32c25eb2f4834bf71][github hosted json, viewable as html at nbviewer]]
- [[http://cgroll.github.io/julia_language_features/#/][github hosted html slideshow]]

Other examples:
- [[http://nbviewer.ipython.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%205%20-%20Rich%20Display%20System.ipynb][embedding rich multimedia content]]
- [[http://nbviewer.ipython.org/gist/bpostlethwaite/7551139][embedding interactive plots through plotly]]


** TimeData package                                                   :notes:
introducing my package

