#+TITLE: Optimal portfolio selection and the problem of estimating return moments
#+AUTHOR: Christian Groll
#+DATE: 1. July 2014

#+CATEGORY: financial_econometrics
#+TAGS: asset_mgmt, Markowitz, presentation
#+DESCRIPTION: analyse performance of Markowitz portfolios 

#+LaTeX_CLASS: beamer
#+BEAMER_THEME: Frankfurt

#+LATEX_HEADER: \usepackage{amsmath}
#+LaTeX_HEADER: \usepackage{geometry}
#+LaTeX_HEADER: \usepackage{subfigure}
#+LaTeX_HEADER: \usepackage{graphicx}
#+LaTeX_HEADER: \usepackage{caption}

#+OPTIONS: d:nil
#+OPTIONS: H:2
#+OPTIONS: toc:nil
#+OPTIONS: todo:t
#+OPTIONS: tags:nil
#+OPTIONS: skip:on
#+OPTIONS: ^:nil
#+OPTIONS: eval:never-export
#+EXCLUDE_TAGS: notes

#+PROPERTY: exports both
#+PROPERTY: results output
#+PROPERTY: tangle yes
#+PROPERTY: dir ./src_results/


#+BEGIN_SRC comment :eval never :exports none
the following line does include toc after each section!
however, preview-latex does not work with it!
#+startup: beamer
#+LATEX_HEADER: \setbeamertemplate{footline}[page number] 
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}
#+LATEX_HEADER: \subtitle{{\color{red} work in progress}}
#+END_SRC

** Motivation
*** traditional notion of risk management
estimation of risk for *given* and *immutable* portfolio composition 

*** proceed with list without box                           :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
- unrealistic (especially for longer horizons):
  - portfolio managers most likely adapt if some asset's risk
    increases relative to others 
  - some investment strategies are explicitly build on portfolio
    re-balancing (duration-based hedging strategies) 

- no guideline on portfolio selection itself: what is optimal
  investment strategy if risk is taken into account 

$\Rightarrow$ asset management as a natural extension to risk
management (Solvency II)


** Motivation
Original intention:
- Markowitz
- factor models
  - reduce dimensions
  - robust estimation of covariance matrix
  - interpret-able structure $\Rightarrow$ false sense of control
    through linear sensitivities

Crucial part of Markowitz: expected returns 
*** Asset pricing theory
- better estimation
- reveal time-variation
$\Rightarrow$ predictability?


** Motivation                                                         :notes:
Hence, I did set up to get acquainted with asset management
- Markowitz: Jasic did wake my interest
- factor models:
  - dimension reduction: market-wide driving factors
  - interpret-able structure required for actively intervening and
    selecting assets
  - industry standard

First moments: I didn't really spent a lot of attention on them

How much information is in conditional expectations? Does it allow
predictability? 
- asset pricing / return predictability usually only slightly referred
  to 
- link to Benjamin's talk 
  - compared to his results, my talk will be quite unimpressive
  - think about basics: what patterns exist in first moments of assets 


** Outline
#+LaTeX: \tableofcontents

* Asset pricing


** Basic assumption 

Following \cite{rv_coch_2009_asset_pricing}: consumption based model

- people are *expected utility maximizers*: with future wealth $X$ and
  utility function $U$, the optimization problem is

$$\underset{\xi}{\max}\ \mathbb{E}[U(X(\xi))]$$


- people are *risk-averse*: utility $U$ increases with money ($U'>0$),
  but marginal utility of money decreases ($U''<0$)

** Risk-aversion                                                      :notes:
"We dislike vast uncertainty in lifetime wealth because a dollar that
helps us avoid poverty is more valuable than a dollar that helps us
become very rich." \cite{rv_rabin_2000_risk_aversion_expected_theory} 

** Concave utility
- due to concavity, uncertainty inherent to future wealth negatively
  affects expected utility

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/concave_utility.jpg}
#+LATEX: \end{figure}

#+BEGIN_LaTeX
   \begin{itemize}
   \item[$\Rightarrow$] for given expectation, cash flow distributions with 
     lower volatility are preferred 
   \end{itemize}
#+END_LaTeX


** Basic assumption notes                                             :notes:

- builds on Cochrane's consumption based model

- any additional euro to profits is worth less utility than any
  additional lost euro -> better formulation

** Consequences for wealth components

#+BEGIN_LaTeX
   \action<+->{Components of future wealth:}
   \begin{itemize}
   \item<+-> assets: prices, dividends
     \begin{itemize}
     \item[$\Rightarrow$]<+-> if assets are unique component: higher asset
       volatility needs to be compensated through higher expected returns
     \end{itemize}
   \end{itemize}
#+END_LaTeX

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02.jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(1).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(2).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(3).jpg}
#+LATEX: \end{figure}


** Consequences for wealth components

If future wealth is completely determined through assets:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(4).jpg}
#+LATEX: \end{figure}

** Consequences for wealth components

If all market participants derive the same utility:

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.6\linewidth]{unreplicatable_pics/return_risk_tradeoff_02(5).jpg}
#+LATEX: \end{figure}

$\Rightarrow$ assets have *different expected returns*, but *equal
expected utility* 

** Notes                                                              :notes:
Picture only shows what future wealth is worth to me. Prices would be
determined through supply and demand at the market. 

If prices coincide with my own appreciation, both assets have
different expected returns, but equal expected utility.

Also: what happens, if volatility changes, while I already have the
asset? 
- price decreases
- given new price level, expected return increases
- given old price level, expected return stays the same, but
  volatility has increased

** Wealth components

#+BEGIN_LaTeX
   Components of future wealth:
   \begin{itemize}
   \item<+-> assets: prices, dividends
     \begin{itemize}
     \item[$\Rightarrow$] if assets are unique component: higher portfolio
       volatility needs to be compensated through higher expected returns
       (\alert{Markowitz})
     \item[$\Rightarrow$]<+-> if all market participants hold all assets:
       \begin{itemize}
       \item portfolio volatility directly depends on asset correlations
       \item compensation for systemic risk only (\alert{CAPM})
       \end{itemize}
     \item[$\Rightarrow$]<+-> \alert{too simplistic}: asset cash flows
       are not the only determinant of your future wealth
     \end{itemize}
   \item<+-> job income 
   \item<+-> losses due to catastrophic events
   \item[$\Rightarrow$]<+-> utility is derived from \alert{overall} cash
     flow distribution: hedge individual components to diminish overall
     volatility 
   \end{itemize}
#+END_LaTeX


** Examples: choose your preferred asset
Given two assets *A* and *B* with *identical* return distributions
($F_{A}\sim F_{B}$), which one would you prefer?

#+BEGIN_LaTeX
   \begin{itemize}
   \item<+-> You are working for Microsoft. Stock A is of Microsoft, while
     stock B is of Walmart.
   \item<+-> You have property within an earthquake zone. Stock A is of
     Walmart, stock B is of a large reinsurance company.
   \end{itemize}
   
   \begin{block}{Investment rule}<+->
     All other things equal, you prefer assets that are valuable when you
     need them.
   \end{block}
#+END_LaTeX


** Further explanation of "when"                                      :notes:
In other words: if an asset tends to have its low price events exactly
when you would need it, then you would require compensation for this
fact. 

"When" could mean:
- a given point in time -> evolution up to this event does not matter
  (10 year bond)
- a given state of nature -> need to sell asset only when I lose job 

** Three types of risk
Risks, that
- *only you have*, but nobody else: assets correlated with your risk
  generate lower expected utility
- *you and everybody else has*: assets correlated with these risks
  exhibit higher expected returns to cause same level of utility
- *everybody else has, but you don't*: assets correlated with these
  risks exhibit higher expected returns, and also generate higher
  levels of utility $\Rightarrow$ *investment opportunity*

** CAPM remarks                                                       :notes:

Risks that only you have: idiosyncratic risk
- not compensated
- assume you are holding single asset
  - single asset with $\beta=0$ 
  - asset volatility largely drives overall volatility of utility
  - you would want compensation on this risk!

CAPM holds, if all wealth arises from assets only, and all investors
invest in all assets. If we switch to a world with multiple wealth
components, should we still expect risk premiums on $\beta$ values?
- assets still could make up a large fraction of overall wealth
- and: high $\beta$ values also correlate with other important
  components: job!

Risks that everybody has: intuitive $\beta$ explanation
- recession increases likelihood of job losses
- in case of job loss, fall back on assets
- recession also decreases asset prices
- hence: assets are comparatively worthless when they are needed most 
- extra compensation

** More realistic factors: Fama / French
- if we were to hedge personal risks with assets, would we have to
  model complete utility function?
- personal risks (job income - temporary worker vs civil service with
  job guarantee, catastrophic events) are usually better
  hedge through insurance
- what would be real risk factors that one would tried to hedge /
  avoid with assets?

- real world factors do not provide such an easy interpretation: Fama
  / French 

** Pricing anomalies
Fama French model
\cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 

- average returns are said to be related to firm characteristics:
  - size
  - earnings / price
  - cash flow / price
  - book-to-market equity
  - past sales growth
  - long-term and short-term past return
- explanation: 
  - CAPM fails (anomalies)
  - consumption based model?

** Fama French three factor model

Time series regression: index t?!
$$R_{i}-R_{f}=\alpha_{i}+b_{i}(R_{M}-R_{f}) + s_{i}SMB + h_{i}HML + \epsilon_{i}$$

$$\mathbb{E}[R_{i}]- R_{f}=b_{i}  \left( \mathbb{E}[R_{M}-R_{f}] \right) +
s_{i}\mathbb{E}[SMB] + h_{i}\mathbb{E}[HML]$$

HML: proxy for relative stress: 
- weak firms with persistently low earnings tend to have high BE/ME
  (comparatively low prices) and positive slopes on HML 


** Momentum
- firms with low long-term returns tend to have higher future returns
  \cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 
- short-term returns tend to continue \cite{rv_fama_fren_1996_multifactor_explanations_asset_pricing_anomalies} 

through FF3: stocks with low long-term past returns (losers) tend to
have positive SMB and HML slopes (they are smaller and relatively
distressed) 
- continuation of short-term returns not explained by FF3

SMB and HML mimic combinations of two underlying risk factors or state
variables of special hedging concern to investors.

** Consequences for Markowitz
1. you are not only interested in $\mu$ and $\Sigma$, but also in the
  dependency between your portfolio and your other risks
-> sole $\mu$-$\Sigma$ optimization is not enough!
-> how do we incorporate this into Markowitz

2. knowledge about other people's risks could improve our estimation
   of $\mu$ and $\Sigma$ -> assets that relate to risks of everybody
   should exhibit higher returns

3. if you have different concerns than the market, you could get
   higher expected returns that translate into comparatively even
   higher utility


** Consequences for Markowitz
- market risk -> penalized through correlation
- idiosyncratic risk -> penalized through high volatility, in the
  limit vanishing, as one would expect
- growth risk -> not incorporated! Would we like to?
- any risk that we have besides market risk: not incorporated
- what would be your risks? (Hard to tell)

** Incorporating additional risks
- how would we incorporate this into Markowitz?
  - model complete distribution with all components?
  - model assets, but adapt their return characteristics (risk neutral
    probabilities) within optimization routine? 
    - artificially scale down $\mu$ factor return of other risks?
- control sensitivities ex-post?

** No additional risks
If we do not bother about it at all, it still could help in better
estimation of return characteristics.


Risk examples (except market risk $\beta$) are made up for intuition,
but we really observe larger returns on assets with some patterns. (Of
course: size, growth, momentum)

Can they be explained through utility theory? 
If they require higher compensation, do you require higher
compensation also, or could you aggressively exploit possibilities of
higher expected utility?



** Risk management                                                    :notes:
Also, it should matter to you, when you exceed your value-at-risk ->
Re-financing costs

** Pitfalls of utility theory
- in our models risk aversion usually is captured through concave
  utility function over wealth
- problem: \cite{rv_rabin_2000_risk_aversion_expected_theory}
  - turning down a modest-stakes gamble means that the marginal
    utility of money must diminish very quickly for small changes in
    wealth
  - anything but virtual risk neutrality over modest stakes implies
    manifestly unrealistic risk aversion over large stakes 

$\Rightarrow$ utility theory unable to replicate human behavior over
large range of wealth levels?

** paper name                                                         :notes:
Risk aversion and expected-utility theory: A calibration theorem.

** Decay of marginal utility of money
*** Question 
How much is the 100th dollar worth compared to the 1000th?

$$ U(\$(100)) \cdot c = U(\$(1000)) $$

*** proceed with list without box                           :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
You have 100\$. Let's assume that you would turn down the following
game:
- heads: you *lose* 10\$
- tails: you *win* 11\$
What can be inferred about the decay of marginal utility of money? 

** Decay of marginal utility of money

what does refraining from participation $\Leftrightarrow$ 
$$0.5\sum_{i=91}^{100} U(\$(i)) >0.5\sum_{i=101}^{111} U(\$(i))$$

tell us about $$U(\$(91))\cdot c = U(\$(111))?$$

#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=0.7\linewidth]{unreplicatable_pics/pitfalls_utility_theory_04.jpg}
#+LATEX: \end{figure}

** Decay of marginal utility of money

Due to
\begin{align*}
10\cdot U(\$(91)) &>\sum_{i=91}^{100} U(\$(i)) \\
&>\sum_{i=101}^{111} U(\$(i)) \\
&> 11\cdot U(\$(111))
\end{align*}

we get 
$$U\left(\$(91)\right) \frac{10}{11}> U\left(\$(111)\right)$$

And, still rejecting the game with initial wealth 121\$:
$$U(\$(91)) \left( \frac{10}{11} \right)^{2}> U(\$(131))$$

** Decay of marginal utility of money
#+LATEX: \begin{figure}[htbp]
#+LATEX:     \centering
#+LATEX:     \includegraphics[width=\linewidth]{unreplicatable_pics/rabin_table.png}
#+LATEX: \end{figure}



** Fama French
- allegedly, some common risk factors could be identified: Fama /
  French 
- no volatility compensation: if everybody else has a large and
  diversified portfolio, they do not bother about idiosyncratic risks 
- factor models (industry standard)

- forecasting returns:
  - allegedly, according to Cochrane, future annual returns could be
    forecast through dividend price ratios
  - consequences for higher frequency returns?
    - simple shift of means is not sufficient!

* Markowitz
** General Markowitz problems
Problems related to asset pricing theory: 
- estimation problems for \mu
- sole $\mu$-$\Sigma$ optimization is not enough
- multi-period extension
- estimation risk (overconfidence / bootstrap)
- mean-variance efficiency does not equal utility maximization 

** Overconfidence
expert vs statistical overconfidence

** Problems with utility
- how does Markowitz work with / relate to asset pricing?
  - for risks that everybody else has but you don't, Markowitz will
    correctly find a good mean-vola ratio and invests into them
  - for risks that only you have, Markowitz does not notice that
    prevailing risk-return ratio is not sufficient to compensate you
    for it
  - risks that everybody has: 
    - usually picked due to better risk-return ratio
    - but: high correlation to other assets could make good
      risk-return ratio undesired

** Using asset pricing theory for better moment estimates

* Asset predictability
- incorporating low frequency information into high frequency data 

* Julia / github

** TimeData package
introducing my package

* References                                                       :noexport:
#+LATEX: \bibliographystyle{apalike}
#+LATEX: \bibliography{references.bib}
